### ISSUE TITLE
Crash with Quark

### ISSUE THREAD

**Issue by Zoofule** [iamshift/BigExtras#10]
**Mod Version:** 1.6.2
**Mod Loader:** Forge 4031354

**How to replicate:**
- Install Big Extras
- Install Quark 3.2-358
- Install Quark Oddities - 1.18

**Extra info**
- ATLauncher log, didn't generate proper forge logs.

> [07/15/2022 11:13:25 AM] Preparing for launch!
> [07/15/2022 11:13:27 AM] Launching pack Minecraft 1.18.2 for Minecraft 1.18.2
> [07/15/2022 11:13:27 AM] Logging into Minecraft!
> [07/15/2022 11:13:27 AM] Loader: Forge 40.1.54
> [07/15/2022 11:13:27 AM] Mods:
> [07/15/2022 11:13:27 AM]  - \AutoRegLib-1.7-53.jar
> [07/15/2022 11:13:27 AM]  - \bigextras-1.6.2.jar
> [07/15/2022 11:13:27 AM]  - \cloth-config-6.2.62-forge.jar
> [07/15/2022 11:13:27 AM]  - \Controlling-forge-1.18.2-9.0+21.jar
> [07/15/2022 11:13:27 AM]  - \farsight-1.18.2-1.9.jar
> [07/15/2022 11:13:27 AM]  - \geckolib-forge-1.18-3.0.28.jar
> [07/15/2022 11:13:27 AM]  - \Jade-1.18.2-forge-5.2.3.jar
> [07/15/2022 11:13:27 AM]  - \jei-1.18.2-9.7.0.209.jar
> [07/15/2022 11:13:27 AM]  - \lavasponge-1.1.6-1.18.2.jar
> [07/15/2022 11:13:27 AM]  - \LibraryFerret-Forge-1.18.2-2.0.0.jar
> [07/15/2022 11:13:27 AM]  - \MouseTweaks-forge-mc1.18-2.21.jar
> [07/15/2022 11:13:27 AM]  - \OreExcavation-1.10.162.jar
> [07/15/2022 11:13:27 AM]  - \Quark-3.2-358.jar
> [07/15/2022 11:13:27 AM]  - \QuarkOddities-1.18.jar
> [07/15/2022 11:13:27 AM]  - \sophisticatedbackpacks-1.18.2-3.17.10.621.jar
> [07/15/2022 11:13:27 AM]  - \sophisticatedcore-1.18.2-0.3.7.59.jar
> [07/15/2022 11:13:27 AM]  - \sophisticatedstorage-1.18.2-0.3.4.49.jar
> [07/15/2022 11:13:27 AM]  - \TerraBlender-forge-1.18.2-1.1.0.102.jar
> [07/15/2022 11:13:27 AM]  - \World Stripper-1.18.2-3.1.0.jar
> [07/15/2022 11:13:27 AM]  - \XaerosWorldMap_1.25.1_Forge_1.18.2.jar
> [07/15/2022 11:13:27 AM]  - \Xaeros_Minimap_22.11.1_Forge_1.18.2.jar
> [07/15/2022 11:13:27 AM] Launching Minecraft with the following arguments (user related stuff has been removed): [USERSDIR\runtimes\minecraft\java-runtime-beta\windows-x64\java-runtime-beta\bin\javaw, -XX:-OmitStackTraceInFastThrow, -Xms256M, -Xmx8192M, -XX:MetaspaceSize=256M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dlog4j.configurationFile=USERSDIR\assets\log_configs\client-1.12.xml, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Dos.name=Windows 10, -Dos.version=10.0, -Xss1M, -Djava.library.path=USERSDIR\temp\natives-91ff6ac61b4342718f37db8613ae6b6f, -Dminecraft.launcher.brand=ATLauncher, -Dminecraft.launcher.version=3.4.18.2, -cp, USERSDIR\libraries\cpw\mods\securejarhandler\1.0.3\securejarhandler-1.0.3.jar;USERSDIR\libraries\org\ow2\asm\asm\9.2\asm-9.2.jar;USERSDIR\libraries\org\ow2\asm\asm-commons\9.2\asm-commons-9.2.jar;USERSDIR\libraries\org\ow2\asm\asm-tree\9.2\asm-tree-9.2.jar;USERSDIR\libraries\org\ow2\asm\asm-util\9.2\asm-util-9.2.jar;USERSDIR\libraries\org\ow2\asm\asm-analysis\9.2\asm-analysis-9.2.jar;USERSDIR\libraries\net\minecraftforge\accesstransformers\8.0.4\accesstransformers-8.0.4.jar;USERSDIR\libraries\org\antlr\antlr4-runtime\4.9.1\antlr4-runtime-4.9.1.jar;USERSDIR\libraries\net\minecraftforge\eventbus\5.0.3\eventbus-5.0.3.jar;USERSDIR\libraries\net\minecraftforge\forgespi\4.0.10\forgespi-4.0.10.jar;USERSDIR\libraries\net\minecraftforge\coremods\5.0.1\coremods-5.0.1.jar;USERSDIR\libraries\cpw\mods\modlauncher\9.1.3\modlauncher-9.1.3.jar;USERSDIR\libraries\net\minecraftforge\unsafe\0.2.0\unsafe-0.2.0.jar;USERSDIR\libraries\com\electronwill\night-config\core\3.6.4\core-3.6.4.jar;USERSDIR\libraries\com\electronwill\night-config\toml\3.6.4\toml-3.6.4.jar;USERSDIR\libraries\org\apache\maven\maven-artifact\3.6.3\maven-artifact-3.6.3.jar;USERSDIR\libraries\net\jodah\typetools\0.8.3\typetools-0.8.3.jar;USERSDIR\libraries\net\minecrell\terminalconsoleappender\1.2.0\terminalconsoleappender-1.2.0.jar;USERSDIR\libraries\org\jline\jline-reader\3.12.1\jline-reader-3.12.1.jar;USERSDIR\libraries\org\jline\jline-terminal\3.12.1\jline-terminal-3.12.1.jar;USERSDIR\libraries\org\spongepowered\mixin\0.8.5\mixin-0.8.5.jar;USERSDIR\libraries\org\openjdk\nashorn\nashorn-core\15.3\nashorn-core-15.3.jar;USERSDIR\libraries\cpw\mods\bootstraplauncher\1.0.0\bootstraplauncher-1.0.0.jar;USERSDIR\libraries\net\minecraftforge\fmlloader\1.18.2-40.1.54\fmlloader-1.18.2-40.1.54.jar;USERSDIR\libraries\com\mojang\logging\1.0.0\logging-1.0.0.jar;USERSDIR\libraries\com\mojang\blocklist\1.0.10\blocklist-1.0.10.jar;USERSDIR\libraries\com\mojang\patchy\2.2.10\patchy-2.2.10.jar;USERSDIR\libraries\com\github\oshi\oshi-core\5.8.5\oshi-core-5.8.5.jar;USERSDIR\libraries\net\java\dev\jna\jna\5.10.0\jna-5.10.0.jar;USERSDIR\libraries\net\java\dev\jna\jna-platform\5.10.0\jna-platform-5.10.0.jar;USERSDIR\libraries\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0-beta4.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-slf4j18-impl\2.17.0\log4j-slf4j18-impl-2.17.0.jar;USERSDIR\libraries\com\ibm\icu\icu4j\70.1\icu4j-70.1.jar;USERSDIR\libraries\com\mojang\javabridge\1.2.24\javabridge-1.2.24.jar;USERSDIR\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;USERSDIR\libraries\io\netty\netty-all\4.1.68.Final\netty-all-4.1.68.Final.jar;USERSDIR\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;USERSDIR\libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar;USERSDIR\libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;USERSDIR\libraries\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;USERSDIR\libraries\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;USERSDIR\libraries\com\mojang\brigadier\1.0.18\brigadier-1.0.18.jar;USERSDIR\libraries\com\mojang\datafixerupper\4.1.27\datafixerupper-4.1.27.jar;USERSDIR\libraries\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;USERSDIR\libraries\com\mojang\authlib\3.3.39\authlib-3.3.39.jar;USERSDIR\libraries\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;USERSDIR\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;USERSDIR\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;USERSDIR\libraries\org\apache\httpcomponents\httpcore\4.4.14\httpcore-4.4.14.jar;USERSDIR\libraries\it\unimi\dsi\fastutil\8.5.6\fastutil-8.5.6.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-api\2.17.0\log4j-api-2.17.0.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-core\2.17.0\log4j-core-2.17.0.jar;USERSDIR\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;USERSDIR\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;USERSDIR\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;USERSDIR\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;USERSDIR\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;USERSDIR\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;USERSDIR\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;USERSDIR\libraries\com\mojang\text2speech\1.12.4\text2speech-1.12.4.jar;USERSDIR\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2-natives-windows.jar;USERSDIR\libraries\com\mojang\text2speech\1.12.4\text2speech-1.12.4-natives-windows.jar;USERSDIR\libraries\net\minecraft\client\1.18.2\client-1.18.2.jar, -DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,client-extra,fmlcore,javafmllanguage,lowcodelanguage,mclanguage,forge-,1.18.2.jar,client-1.18.2.jar, -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar,java-objc-bridge-1.0.0.jar, -DlibraryDirectory=USERSDIR\libraries, -p, USERSDIR\libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar;USERSDIR\libraries/cpw/mods/securejarhandler/1.0.3/securejarhandler-1.0.3.jar;USERSDIR\libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar;USERSDIR\libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar;USERSDIR\libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar;USERSDIR\libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar;USERSDIR\libraries/org/ow2/asm/asm/9.2/asm-9.2.jar, --add-modules, ALL-MODULE-PATH, --add-opens, java.base/java.util.jar=cpw.mods.securejarhandler, --add-exports, java.base/sun.security.util=cpw.mods.securejarhandler, --add-exports, jdk.naming.dns/com.sun.jndi.dns=java.naming, cpw.mods.bootstraplauncher.BootstrapLauncher, --username, REDACTED, --version, 1.18.2, --gameDir, USERSDIR\instances\TestThings, --assetsDir, USERSDIR\assets, --assetIndex, 1.18, --uuid, REDACTED, --accessToken, REDACTED, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.54, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width=854, --height=480]
> [07/15/2022 11:13:31 AM] [main/INFO] ModLauncher running: args [--username, **MINECRAFTUSERNAME**, --version, 1.18.2, --gameDir, **USERSDIR**\instances\TestThings, --assetsDir, **USERSDIR**\assets, --assetIndex, 1.18, --uuid, **UUID**, --accessToken, â�„â�„â�„â�„â�„â�„â�„â�„, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.54, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width=854, --height=480]
> [07/15/2022 11:13:31 AM] [main/INFO] ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
> [07/15/2022 11:13:31 AM] [main/INFO] SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Zoo/AppData/Roaming/ATLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file AutoRegLib-1.7-53.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file bigextras-1.6.2.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file cloth-config-6.2.62-forge.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file Controlling-forge-1.18.2-9.0+21.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file farsight-1.18.2-1.9.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file geckolib-forge-1.18-3.0.28.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file Jade-1.18.2-forge-5.2.3.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file jei-1.18.2-9.7.0.209.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file lavasponge-1.1.6-1.18.2.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file LibraryFerret-Forge-1.18.2-2.0.0.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file MouseTweaks-forge-mc1.18-2.21.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file OreExcavation-1.10.162.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file Quark-3.2-358.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file QuarkOddities-1.18.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file sophisticatedbackpacks-1.18.2-3.17.10.621.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file sophisticatedcore-1.18.2-0.3.7.59.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file sophisticatedstorage-1.18.2-0.3.4.49.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file TerraBlender-forge-1.18.2-1.1.0.102.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file World Stripper-1.18.2-3.1.0.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file Xaeros_Minimap_22.11.1_Forge_1.18.2.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:31 AM] [main/INFO] Found mod file XaerosWorldMap_1.25.1_Forge_1.18.2.jar of type MOD with locator {mods folder locator at **USERSDIR**\instances\TestThings\mods}
> [07/15/2022 11:13:32 AM] [main/INFO] Found mod file fmlcore-1.18.2-40.1.54.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@70f43b45
> [07/15/2022 11:13:32 AM] [main/INFO] Found mod file javafmllanguage-1.18.2-40.1.54.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@70f43b45
> [07/15/2022 11:13:32 AM] [main/INFO] Found mod file lowcodelanguage-1.18.2-40.1.54.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@70f43b45
> [07/15/2022 11:13:32 AM] [main/INFO] Found mod file mclanguage-1.18.2-40.1.54.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@70f43b45
> [07/15/2022 11:13:32 AM] [main/INFO] Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@70f43b45
> [07/15/2022 11:13:32 AM] [main/INFO] Found mod file forge-1.18.2-40.1.54-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@70f43b45
> [07/15/2022 11:13:35 AM] Exception in thread "main" java.lang.module.ResolutionException: Modules bigextras and quark export package vazkii.quark.api to module minecraft
> [07/15/2022 11:13:35 AM] 	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
> [07/15/2022 11:13:35 AM] 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
> [07/15/2022 11:13:35 AM] 	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
> [07/15/2022 11:13:35 AM] 	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
> [07/15/2022 11:13:35 AM] 	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
> [07/15/2022 11:13:35 AM] 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
> [07/15/2022 11:13:35 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
> [07/15/2022 11:13:35 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
> [07/15/2022 11:13:35 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
> [07/15/2022 11:13:35 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
> [07/15/2022 11:13:35 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
> [07/15/2022 11:13:35 AM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
> [07/15/2022 11:13:35 AM] 	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
> [07/15/2022 11:13:35 AM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
> [07/15/2022 11:13:35 AM] Checking for updated files!
> 
>

**Comment by shiftthedev** [comment]
Should be fixed in [1.6.3](https://www.curseforge.com/minecraft/mc-mods/big-extras-forge/files/3877154)
