### ISSUE TITLE
Mod Compatibility Bug gives infinite Health.

### ISSUE THREAD

**Issue by Sinogard** [iamshift/BigExtras#11]
**Mod Version:** Latest
**Mod Loader:** Fabric 
I'm not sure why but absorption doesnt seem to have a cooldown, applies instantly, and stacks infinitely.

**How to replicate:**
Eat a golden apple or stand on a nether star block or otherwise gain absorption.

**Extra info**
Blockus adds a block that gives absorption strength and toughness whilst on the block. I have spoken with the dev of that mod and they tracked the issue to this mod. We cant find a config that enables this behavior. It should be noted that anything that gives absorption including golden apples stack the health.
Screenshot shows things off the block and doesn't seem to go away despite logging out
![Screenshot 2023-08-04 063830](https://github.com/shiftthedev/BigExtras/assets/88293626/369da703-cab8-4308-a9b9-5524a7c442b7)
My mod pack where the behavior is easily reproduced. Click and drag into multimc or prism to recreate my instance complete with configs.
https://drive.google.com/file/d/16NJS50Nf5denIUtaG3HPLWb7np7SmZEe/view?usp=drive_link

**Comment by shiftthedev** [comment]
Thanks for reporting. I will look into it.

**Comment by shiftthedev** [comment]
fixed released

**Comment by ArcaneAlloy** [comment]
This bug happens in the Minecraft 1.19.2 [Forge] version too.
Can you fix it there too, please?

Thanks!

**Comment by shiftthedev** [comment]
I'll fix it but can only do it next weekend.

**Comment by ArcaneAlloy** [comment]
Perfect, thank you so much!

**Comment by shiftthedev** [comment]
> This bug happens in the Minecraft 1.19.2 [Forge] version too. Can you fix it there too, please?
> 
> Thanks!

fixed.
