### ISSUE TITLE
Beacon flight turns off every 3 seconds

### ISSUE THREAD

**Issue by DaddySpin** [iamshift/BigExtras#3]
Every time the flight potion effect from the beacon resets from 13 to 16 seconds you loose your flight and you have to reactivate it.

**Comment by shiftthedev** [comment]
This seems to be an incompatibility with [PlayerAbilityLib](https://github.com/Ladysnake/PlayerAbilityLib) and any mod that has it embeded. 
For exemple: Kibe and Requiem

**Comment by DaddySpin** [comment]
Is it possible to fix?

**Comment by shiftthedev** [comment]
> Is it possible to fix?

Not on my end.
But maybe something can be done in the other mod.

**Comment by DaddySpin** [comment]
You going to open a issue with player ability lib?

**Comment by shiftthedev** [comment]
https://github.com/Ladysnake/PlayerAbilityLib/issues/4

**Comment by shiftthedev** [comment]
fixed in version 1.1
