### ISSUE TITLE
Flight effect displayed as negative effect

### ISSUE THREAD

**Issue by DaddySpin** [iamshift/BigExtras#4]
Just nitpicking here, but the flight effect is displayed as a negative effect instead of a positive effect.
it should be displayed on the top row instead of the bottom row.
![image](https://user-images.githubusercontent.com/34575655/96186351-ecab5480-0f00-11eb-936c-9d2a7a8f56ac.png)
![image](https://user-images.githubusercontent.com/34575655/96186977-d5209b80-0f01-11eb-877b-85db1fd55cad.png)

**Comment by shiftthedev** [comment]
fixed in 1.1.1
