### ISSUE TITLE
Couldn't load block tag

### ISSUE THREAD

**Issue by DaddySpin** [iamshift/BigExtras#5]
every time i try to join my world it puts me in safe mode.
This is what i found in the console.

https://pastebin.com/ysZSK7AT

**Comment by DaddySpin** [comment]
This happens when you disable white and black sand in the config.

**Comment by shiftthedev** [comment]
fixed in [1.2](https://www.curseforge.com/minecraft/mc-mods/big-extras-fabric/files/3082918)
