### ISSUE TITLE
Suggestion: Allow rail placement on the normal invisible block.

### ISSUE THREAD

**Issue by MxOrbulent** [iamshift/BigExtras#6]
Allowing rail placement on the normal invisible blocks (the kind that let's all entities fall trough) would make it
possible to build both solid and non-solid rail bridges for all entities. Right now, you can only build non-solid and solid rail bridges for players with the entities block, and solid for all with the n blocks. 
It would be nice to be able to build non-solid rail bridges for all entities.
Also, a invisible block that does let water trough would also be nice since rails can now be waterlogged. Which would make it possible to build underwater rail bridges.
![2021-06-16_12 42 22](https://user-images.githubusercontent.com/64158344/122205362-11910680-ce98-11eb-9807-509c3d21dcdf.png)

**Comment by shiftthedev** [comment]
Thanks for the suggestion. I'll see what can be done.

**Comment by shiftthedev** [comment]
Added in 1.5.1
