### ISSUE TITLE
[Forge] Eating causes a FOV change (not a listed 'feature')

### ISSUE THREAD

**Issue by Gerflargle** [iamshift/BigExtras#8]
**Mod Version:** 1.5.3
**Mod Loader:** Forge 36.1.63

**How to replicate:**
- Eat Any Food: while eating your field of view significantly changes, which can be visually jarring

**Extra info**
Only mods present are BigExtras and the Forge Cloth Config.
For visual reference, two attached images, one just standing, one eating. 

![Reference](https://user-images.githubusercontent.com/8070276/126588862-26b96034-c2ab-420e-b5a0-7e4cef2e6f0f.png)
![Eating](https://user-images.githubusercontent.com/8070276/126588865-c95a7698-f0e7-4cd4-8a5c-b35b2f68851b.png)

**Comment by shiftthedev** [comment]
fixed in [1.5.4](https://www.curseforge.com/minecraft/mc-mods/big-extras-forge/files/3396834)
